### ISSUE TITLE
[SOLVED] Game does not allow saving using this mod

### ISSUE THREAD

**Issue by airriderz15** [mRally2/GRIP2#1]
Hi, I was wondering if there's a way to apply this mod that won't break save games? Can't save any game progress and there are no fixes for this problem anywhere.

**Comment by mRally2** [comment]
Hello airriderz15, thank you for your feedback. I didn’t know applying the custom configs prevents the game from saving. I did all my testing using a completed save. This might be caused due to some sort of anti-cheat protection built into the exe.

If you are willing to test something out do the following:

1. Make a new folder inside your C drive called GRIP2

2. Make a brand new XML file inside the GRIP2 folder named mods.xml and paste inside the following:
< ?xml version="1.0" encoding="utf-8"? >
< ModList >
< Mod Path="C:\GRIP2" / >
< /ModList >

3. Make a folder structure inside GRIP2 with the exact name as inside the game’s directory: cars/models

4. Paste inside models all the folders from my rar

5. Do the following:
Right-click “GRID 2” in the Steam library.
Select “Properties”
Click “Set Launch Options”
Insert “-mod ” followed by the path to your configuration file, e.g. -mod “c:\GRIP2\mods.xml”
Click “Ok”
Run the game.

6. When you are at the pre-frontend menu, if everything goes fine it will make you choose which savefile you want to start the game with. Choose the one that has MOD in it (or something similar)

7. After that, the game will make a brand new savefile exclusively for the mod so you have to start from scratch in the story mode. It cannot transfer the progress from your non modded save. It was made by design like that by codies.

Post here if it saves the progress using this method. Cheers.

**Comment by airriderz15** [comment]
Yes! Finally it saves. Just an addition to your instructions, I had to copy the models folder to the "GRIP2" mod folder, then add the .ctf files for each car. Then in the mod.xml file put the code in the xml on notepad to find the path:

example
"(?xml version="1.0" encoding="utf-8"?)"

"(ModList)"
"(Mod Path="D:\GRIP2\cars\models"/)"
"(/ModList)" 

replacing the parentheses and quotations on the outside with the <> sign
After that putting the mod path in the steam launch: 
example 

-mod "D:\GRIP2\mods.xml"  
Then the game started with a new save.  
Only added what I did since without knowing what to put in the xml file, the game won't launch and will just say "failed to parse xml file" or something like that.

**Comment by mRally2** [comment]
Thanks for testing it out. One thing though. The game should be able to read the .ctf files from my rar pack. You shouldn’t need to copy the whole /models folder and then patch in the files. The BayetasMod does something similar and works fine as far as I know. Also, the game should interpret where the files to be patched are just by giving it the main mod folder path without the need of giving it the full path. Could you check this too?

**Comment by airriderz15** [comment]
> Thanks for testing it out. One thing though. The game should be able to read the .ctf files from my rar pack. You shouldn’t need to copy the whole /models folder and then patch in the files. The BayetasMod does something similar and works fine as far as I know. Also, the game should interpret where the files to be patched are just by giving it the main mod folder path without the need of giving it the full path. Could you check this too?

Yes, it works with just the mod folder. Just tested it and it works by just naming the folder path cars/models without patching the files and copying.

**Comment by mRally2** [comment]
> **SOLUTION**

1. Make a new folder inside your C drive called GRIP2

2. Make a brand new XML file inside the GRIP2 folder named mods.xml and paste inside the following (delete the spaces between < and >):
< ?xml version="1.0" encoding="utf-8"? >
< ModList >
< Mod Path="C:\GRIP2\cars\models" / >
< /ModList >

3. Make a folder structure inside GRIP2 with the exact name as inside the game’s directory: cars/models

4. Paste inside models all the folders from my rar

5. Do the following:
Right-click “GRID 2” in the Steam library.
Select “Properties”
Click “Set Launch Options”
Insert “-mod ” followed by the path to your configuration file, e.g. -mod “c:\GRIP2\mods.xml”
Click “Ok”
Run the game.

6. When you are at the pre-frontend menu, if everything goes fine it will make you choose which savefile you want to start the game with. Choose the one that has MOD in it (or something similar)

7. After that, the game will make a brand new savefile exclusively for the mod so you have to start from scratch in the story mode. It cannot transfer the progress from your non modded save. It was made by design like that by codies.

**Comment by tukykarmakar** [comment]
For those who don't have the game in Steam, you can add the game to Steam as a non-Steam game and follow the steps above.

Else, if you want to keep Steam out of the equation completely, you can follow the steps below--
1. Create a shortcut of the grid2.exe file.
2. Right-click on the shortcut, go to Properties > Shortcut.
3. Add the -mod parameter and the path at the end of the text in the Target field.
![image](https://github.com/mRally2/GRIP2/assets/42614682/f3138d51-3492-4b1a-847e-bfbcd1a668ba)

**Comment by Brawlar** [comment]
Hey tukkarmaker, are you able to help me? Because although I have the game on Steam, I can't path to C:\GRIP2\mods.xml. because apparently it's saying D:\GRIP2\mods.xml doesn't exist, even though it's supposed to be going to my C drive...

**Comment by Illidan1943** [comment]
> 5\. Insert “-mod ” followed by the path to your configuration file, e.g. -mod “c:\GRIP2\mods.xml”

Years late, but don't add the quotes to the path if the game is trying to launch the AVX executable as the game won't be able to open it

**Comment by HamzaKz786** [comment]
Im sorry but i did everything you guys said, and for some reason it doesn't work for me.
My thought is that the shortcut isn't reading the 
( -mod "c:\grip2\mods.xml) command but idk.

**Comment by tukykarmakar** [comment]
@HamzaKz786 try getting the path by Shift+Right Click on the file > Copy as path. It will copy the path of the file to your clipboard and you can paste from there. If what you put in the shortcut is exactly what you wrote here, then you're missing the closing quotes (") and C drive should be in uppercase.

**Comment by HamzaKz786** [comment]
![Image](https://github.com/user-attachments/assets/2f7049b3-7675-4af4-8b67-76348fdf1059)
![Image](https://github.com/user-attachments/assets/4d2c371d-c01b-4676-8091-1e6d330ba523)
Sooo... it still doesn't work.

**Comment by tukykarmakar** [comment]
@HamzaKz786 how do you know that it's not working? Is it not showing anything saying "MOD" when loading the save files?

**Comment by HamzaKz786** [comment]
@tukykarmakar 
how do i know? 
i go in the game and started a new save. when the first race starts i wave the car left and right to see if the mod is working. 
is it showing anythinh sayind "MOD"?
where does it show that?

**Comment by tukykarmakar** [comment]
@HamzaKz786 continue doing the intro activities till you've entered your name, nationality, age, difficulty, etc. Then when you get the choice to start your first race, you can back out and quit the game. The game should've saved your details by now.

If you were playing the intro with a mod activated, when you load up the game again, it will ask you to select a save or create a new save. THIS is where you can see the save game has the word "MOD" in it. The name of the save should be like this--
`MOD | <YOUR NAME> - GRID 2 Career Races: #, Online Races: #`
This is how you know that the mod is working.

If you're expecting the handling to drastically change back to how it was in Racedriver: GRID or other GRID games, then I'm afraid it's not like that. This mod improves the handling to have more grip, but it's not a full swap out or replacement of the physics from other GRID games. Unfortunately, there will be a good amount of drifting still left over.

**Comment by HamzaKz786** [comment]
@tukykarmakar ooooow i remember that happening when i used to put the files directly in the games directory. 
but i remember one time i tried the bayetas mod with this same method and it worked but now with GRIP2 it doesn't for some reason? but i think i've bothered you long enough with this, thank you for the help :)
